[package]
name = "now-client"
version = "0.1.0"
edition = "2021"


[dependencies]
iced = { version = "0.12.1" }
reqwest = { version = "0.12.4", features = ["blocking"]}
base64 = "0.22.1"
serde_json = "1.0.117"